[package]
name = "aws-sig-auth"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.2"
aws-sigv4 = { git = "https://github.com/rcoh/sigv4", rev = "05f90abc02a868cb570ed3006d950947cc0898b0" }
aws-auth = { path = "../aws-auth" }

[dev-dependencies]
tokio = { version = "1", features = ["full"]}
