[package]
name = "smithy-stream"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
description = "Support for Smithy streaming protocols"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-body = "0.4.0"
futures-core = "0.3.12"
pin-utils = "0.1.0"
bytes = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0" }
