[package]
name = "inlineable"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
description = """
This modules of this crate are intended to be inlined directly into the SDK as needed (TODO)
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
proptest = "0.10.1"
