[package]
name = "inlineable"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
description = """
The modules of this crate are intended to be inlined directly into the SDK as needed.
"""

[dependencies]
"serde" = { version ="1", features = ["derive"] }
"smithy-types" = { version = "0.0.1", path = "../smithy-types" }
"serde_json" = "1"

[dev-dependencies]
proptest = "0.10.1"
serde_json = "1"
