[package]
name = "high-level-prototype"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamodb = { path = "../../build/aws-sdk/dynamodb" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper"}
tower = "0.4.6"
tokio = { version = "1", features = ["full"] }
http = "0.2.3"
hyper = "0.14.4"
smithy-http = { path = "../../build/aws-sdk/smithy-http"}
hyper-tls = "0.5.0"
