[package]
name = "kms-reencrypt-data"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"
description = "Code example of the KMS ReEncrypt API"

[dependencies]
kms = { path = "../../build/aws-sdk/kms" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper" }
tokio = { version = "1", features = ["full"]}
base64 = "0.13.0"
clap = { version = "2.33.3" }
# optional
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
